version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules inside the container
      - /app/dist  # Ensure dist directory updates inside container
    command: ["sh", "-c", "npm run build && npx nodemon --watch dist --ext js,json --exec node dist/server.js"]
    

  frontend:
    build: ../client
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../client:/app  # Fixed path typo (..client -> ../client)
      - /app/node_modules
    environment:
      - VITE_API_URI=http://localhost:3000

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
